    /**
     * Assert that the provided exception's message is the same as the one provided. If the messages
     * don't match then junit's fail(...) method is called, if they do match then the original
     * exception is re-thrown to be handled by the calling code - usually by a Test(expected =
     * ***Exception.class) annotation.
     *
     * @param exception The exception you want to check.
     * @param expectedMessage The message you expect the exception to include.
     * @throws Exception Throws the original exception back if the message DOES match. This means
     *     you still need to have the annotation: Test(expected = ***Exception.class)
     */
    public static void assertExceptionMessage(Exception exception, String expectedMessage)
            throws Exception {
        String actualMessage = exception.getMessage();
        if (actualMessage.compareTo(expectedMessage) != 0) {
            fail(
                    String.format(
                            "Expected %s to say: '%s' but got: '%s'",
                            exception.getClass().getSimpleName(), expectedMessage, actualMessage));
        }

        throw exception;
    }

