    /**
     * This test should fail with an IOException because there is actually no such JNDI to connect
     * to, but the factory lookup will have succeeded before * throwing the exception.
     *
     * @throws IOException always with the message: "Cannot find JNDI data source:
     *     java:comp/env/jdbc/geotools"
     */
    @Test(expected = IOException.class)
    public void testCanGetMSdataStore() throws IOException {
        jndiProps.put("dbtype", "sqlserver");

        // this will fail with the message: "Cannot find JNDI data source:
        // java:comp/env/jdbc/geotools"
        JDBCDataStore dataStore = (JDBCDataStore) DataStoreFinder.getDataStore(jndiProps);
        fail("Expected exception was not thrown");
    }

