    protected void connect() throws Exception {
        super.connect();

        dataStore.setAssociations(true);
    }

